version: "3.9"
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: "cinematheque"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123456789"
    ports:
      - "5432:5432"
    volumes:
      - ./migrations:/migrations
  app:
    build: .
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgres://postgres:123456789@postgres:5432/cinematheque?sslmode=disable"
    volumes:
      - .:/app
